### ISSUE TITLE
Dark Keyboard doesn't work system-wide on iOS 12

### ISSUE THREAD

**Issue by NguyenASang** [tomaszpoliszuk/KeyboardController#6]
Title

**Comment by tomaszpoliszuk** [comment]
Sorry for that & thanks for letting me know - in fact nothing was working on older iOS versions, I'm about to send update to BigBoss in the meantime you can use latest release from [here](https://github.com/tomaszpoliszuk/KeyboardController/releases/tag/1.2.3) 

Fixed in 0e93c19a43e72b239963cf44838d974eb95b5574

**Comment by tomaszpoliszuk** [comment]
@NguyenASang I will close this issue when update will be published on BigBoss (or you can, if you will).

**Comment by NguyenASang** [comment]
@tomaszpoliszuk I tested the latest but it still doesn't work

**Comment by tomaszpoliszuk** [comment]
@NguyenASang just to be sure - version 1.2.2 from BigBoss or 1.2.3 from [Releases](https://github.com/tomaszpoliszuk/KeyboardController/releases/tag/1.2.3)?

**Comment by NguyenASang** [comment]
@tomaszpoliszuk 1.2.3 from Release

**Comment by tomaszpoliszuk** [comment]
Ok, that's weird, give me few days since I have to reinstall system to iOS 12, I've tested both versions on 11.4.1 and indeed 1.2.2 doesn't work, while 1.2.3 is working on it.

While you wait please use [version 1.2.1](http://apt.thebigboss.org/repofiles/cydia/debs2.0/keyboardcontroller_1.2.1.deb).

**Comment by NguyenASang** [comment]
@tomaszpoliszuk Any update ?

**Comment by tomaszpoliszuk** [comment]
Just checked 1.2.3 from BigBoss on iOS 12, everything is working correctly, could you:
- remove Keyboard Controller
- install it again from BigBoss
- if it's still doesn't work, please disable all other tweaks to verify if it's not fault of other tweak conflicting with Keyboard Controller

Let me know results of above tests.

**Comment by NguyenASang** [comment]
it conflicts with Darkmode, it's open source so I hope you can solve it.

https://github.com/turntducky/Dark-System/blob/6aea2e3f9326bd6f431897424530ef24cf41de8a/darkmodefree/Tweak.xm#L1089-L1108

Note: I turned off the dark keyboard option, so the keyboard was forced to light.
You can install `Darkmode (SYSTEM ONLY)` tweak from Twickd repo to test

**Comment by tomaszpoliszuk** [comment]
I'm closing this one (as tweak works correctly on iOS 12) & moving thread to https://github.com/tomaszpoliszuk/KeyboardController/issues/7, please follow that issue for further updates about support for Darkmode tweak
